# cSpell:ignore noninteractive
---
- name: Install Flatpak deb packages
  become: true
  ansible.builtin.apt:
    name:
      - flatpak
    state: present

- name: Upgrade global Flatpak packages
  become: true
  ansible.builtin.command:
    cmd: flatpak update --noninteractive
  register: flatpak_update
  changed_when: flatpak_update.stdout != "Nothing to do."

- name: Clean up global Flatpak
  become: true
  ansible.builtin.command:
    cmd: flatpak uninstall --unused --noninteractive
  register: flatpak_uninstall
  changed_when: flatpak_uninstall.stdout != "Nothing unused to uninstall"

- name: Upgrade user Flatpak packages
  ansible.builtin.command:
    cmd: flatpak update --noninteractive
  register: flatpak_update
  changed_when: flatpak_update.stdout != "Nothing to do."

- name: Clean up user Flatpak
  ansible.builtin.command:
    cmd: flatpak uninstall --unused --noninteractive
  register: flatpak_uninstall
  changed_when: flatpak_uninstall.stdout != "Nothing unused to uninstall"
